apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-display
  labels:
    contrib.eventing.knative.dev/release: devel
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/knative/eventing-contrib/cmd/event_display
