// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloud_events_context.proto

package dev_knative

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CloudEventsContext defines the standard attributes that are always available
// in the CEL evaluation environment. For compatibility reasons, these
// attributes may not be exactly the same as the attributes in the current
// version of the CloudEvents spec.
type CloudEventsContext struct {
	Specversion          string   `protobuf:"bytes,1,opt,name=specversion,proto3" json:"specversion,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Subject              string   `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Schemaurl            string   `protobuf:"bytes,7,opt,name=schemaurl,proto3" json:"schemaurl,omitempty"`
	Datacontenttype      string   `protobuf:"bytes,8,opt,name=datacontenttype,proto3" json:"datacontenttype,omitempty"`
	Datamediatype        string   `protobuf:"bytes,9,opt,name=datamediatype,proto3" json:"datamediatype,omitempty"`
	Datacontentencoding  string   `protobuf:"bytes,10,opt,name=datacontentencoding,proto3" json:"datacontentencoding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudEventsContext) Reset()         { *m = CloudEventsContext{} }
func (m *CloudEventsContext) String() string { return proto.CompactTextString(m) }
func (*CloudEventsContext) ProtoMessage()    {}
func (*CloudEventsContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3df9ee1ac825df6, []int{0}
}

func (m *CloudEventsContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudEventsContext.Unmarshal(m, b)
}
func (m *CloudEventsContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudEventsContext.Marshal(b, m, deterministic)
}
func (m *CloudEventsContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudEventsContext.Merge(m, src)
}
func (m *CloudEventsContext) XXX_Size() int {
	return xxx_messageInfo_CloudEventsContext.Size(m)
}
func (m *CloudEventsContext) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudEventsContext.DiscardUnknown(m)
}

var xxx_messageInfo_CloudEventsContext proto.InternalMessageInfo

func (m *CloudEventsContext) GetSpecversion() string {
	if m != nil {
		return m.Specversion
	}
	return ""
}

func (m *CloudEventsContext) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CloudEventsContext) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CloudEventsContext) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CloudEventsContext) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CloudEventsContext) GetSchemaurl() string {
	if m != nil {
		return m.Schemaurl
	}
	return ""
}

func (m *CloudEventsContext) GetDatacontenttype() string {
	if m != nil {
		return m.Datacontenttype
	}
	return ""
}

func (m *CloudEventsContext) GetDatamediatype() string {
	if m != nil {
		return m.Datamediatype
	}
	return ""
}

func (m *CloudEventsContext) GetDatacontentencoding() string {
	if m != nil {
		return m.Datacontentencoding
	}
	return ""
}

func init() {
	proto.RegisterType((*CloudEventsContext)(nil), "dev.knative.CloudEventsContext")
}

func init() { proto.RegisterFile("cloud_events_context.proto", fileDescriptor_a3df9ee1ac825df6) }

var fileDescriptor_a3df9ee1ac825df6 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0xe9, 0xba, 0xee, 0x76, 0xa7, 0xf8, 0x87, 0x11, 0x64, 0x10, 0x0f, 0x45, 0x3c, 0xf4,
	0x54, 0x04, 0x1f, 0xa1, 0x78, 0xf1, 0xe8, 0x0b, 0x94, 0x34, 0x19, 0x34, 0xda, 0x26, 0xcb, 0x66,
	0x12, 0xf4, 0xb5, 0x7c, 0x42, 0xe9, 0xa8, 0xb8, 0x8a, 0xb7, 0x7c, 0xbf, 0xef, 0x17, 0x86, 0x19,
	0xb8, 0xb0, 0xdb, 0x98, 0xdd, 0x9a, 0x0b, 0x07, 0x49, 0x6b, 0x1b, 0x83, 0xf0, 0xab, 0x2c, 0xfb,
	0x21, 0x4a, 0xc4, 0x99, 0xe3, 0xb2, 0x7c, 0x09, 0x46, 0x7c, 0xe1, 0xab, 0xf7, 0x0a, 0x70, 0xb5,
	0x77, 0xef, 0x54, 0x5d, 0x7d, 0x9a, 0x38, 0x87, 0x59, 0xea, 0xd9, 0x16, 0x1e, 0x92, 0x8f, 0x81,
	0x26, 0xf3, 0xc9, 0xa2, 0x7b, 0x18, 0x23, 0x44, 0xa8, 0xe5, 0xad, 0x67, 0xaa, 0xb4, 0xd2, 0x37,
	0x9e, 0x43, 0x93, 0x62, 0x1e, 0x2c, 0xd3, 0x81, 0xd2, 0xaf, 0x84, 0x04, 0x6d, 0xca, 0x9b, 0x67,
	0xb6, 0x42, 0xb5, 0x16, 0xdf, 0x11, 0x8f, 0xa1, 0xf2, 0x8e, 0x0e, 0x15, 0x56, 0xde, 0xe1, 0x25,
	0x74, 0xc9, 0x3e, 0xf1, 0xce, 0xe4, 0x61, 0x4b, 0xad, 0xe2, 0x1f, 0x80, 0x0b, 0x38, 0x71, 0x46,
	0x8c, 0xae, 0x13, 0x44, 0xc7, 0x4f, 0xd5, 0xf9, 0x8b, 0xf1, 0x1a, 0x8e, 0xf6, 0x68, 0xc7, 0xce,
	0x1b, 0xf5, 0x3a, 0xf5, 0x7e, 0x43, 0xbc, 0x81, 0xb3, 0xd1, 0x47, 0x0e, 0x36, 0x3a, 0x1f, 0x1e,
	0x09, 0xd4, 0xfd, 0xaf, 0xba, 0xaf, 0xa7, 0xcd, 0x69, 0xbb, 0x69, 0xf4, 0x90, 0xb7, 0x1f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xe0, 0x00, 0x3a, 0xb0, 0x66, 0x01, 0x00, 0x00,
}
