// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloud_events_context.proto

package dev_knative

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CloudEventsContext struct {
	Specversion          string   `protobuf:"bytes,1,opt,name=specversion,proto3" json:"specversion,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Schemaurl            string   `protobuf:"bytes,4,opt,name=schemaurl,proto3" json:"schemaurl,omitempty"`
	Datamediatype        string   `protobuf:"bytes,5,opt,name=datamediatype,proto3" json:"datamediatype,omitempty"`
	Datacontenttype      string   `protobuf:"bytes,6,opt,name=datacontenttype,proto3" json:"datacontenttype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudEventsContext) Reset()         { *m = CloudEventsContext{} }
func (m *CloudEventsContext) String() string { return proto.CompactTextString(m) }
func (*CloudEventsContext) ProtoMessage()    {}
func (*CloudEventsContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3df9ee1ac825df6, []int{0}
}

func (m *CloudEventsContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudEventsContext.Unmarshal(m, b)
}
func (m *CloudEventsContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudEventsContext.Marshal(b, m, deterministic)
}
func (m *CloudEventsContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudEventsContext.Merge(m, src)
}
func (m *CloudEventsContext) XXX_Size() int {
	return xxx_messageInfo_CloudEventsContext.Size(m)
}
func (m *CloudEventsContext) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudEventsContext.DiscardUnknown(m)
}

var xxx_messageInfo_CloudEventsContext proto.InternalMessageInfo

func (m *CloudEventsContext) GetSpecversion() string {
	if m != nil {
		return m.Specversion
	}
	return ""
}

func (m *CloudEventsContext) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CloudEventsContext) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CloudEventsContext) GetSchemaurl() string {
	if m != nil {
		return m.Schemaurl
	}
	return ""
}

func (m *CloudEventsContext) GetDatamediatype() string {
	if m != nil {
		return m.Datamediatype
	}
	return ""
}

func (m *CloudEventsContext) GetDatacontenttype() string {
	if m != nil {
		return m.Datacontenttype
	}
	return ""
}

func init() {
	proto.RegisterType((*CloudEventsContext)(nil), "dev.knative.CloudEventsContext")
}

func init() { proto.RegisterFile("cloud_events_context.proto", fileDescriptor_a3df9ee1ac825df6) }

var fileDescriptor_a3df9ee1ac825df6 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x4d, 0x6a, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0xeb, 0x1a, 0x3c, 0xa6, 0x14, 0x66, 0x51, 0x44, 0xe9, 0xc2, 0x94, 0x2e, 0xbc,
	0xf2, 0xa6, 0x47, 0x30, 0xbd, 0x40, 0x2e, 0x60, 0x14, 0x69, 0x20, 0x26, 0xb6, 0x64, 0xa4, 0xb1,
	0x48, 0x6e, 0x99, 0x23, 0x05, 0x4f, 0x02, 0xf9, 0xd9, 0xcd, 0x7c, 0xef, 0xe3, 0xc1, 0x83, 0x2f,
	0x33, 0xfa, 0xc5, 0xf6, 0x94, 0xc8, 0x71, 0xec, 0x8d, 0x77, 0x4c, 0x07, 0x6e, 0xe7, 0xe0, 0xd9,
	0x63, 0x65, 0x29, 0xb5, 0x7b, 0xa7, 0x79, 0x48, 0xf4, 0x73, 0xca, 0x00, 0xbb, 0xd5, 0xfd, 0x17,
	0xb5, 0xbb, 0x98, 0x58, 0x43, 0x15, 0x67, 0x32, 0x89, 0x42, 0x1c, 0xbc, 0x53, 0x59, 0x9d, 0x35,
	0xe5, 0xe6, 0x1e, 0x21, 0x42, 0xce, 0xc7, 0x99, 0xd4, 0x8b, 0x44, 0x72, 0xe3, 0x27, 0x14, 0xd1,
	0x2f, 0xc1, 0x90, 0x7a, 0x15, 0x7a, 0xfd, 0xf0, 0x1b, 0xca, 0x68, 0x76, 0x34, 0xe9, 0x25, 0x8c,
	0x2a, 0x97, 0xe8, 0x06, 0xf0, 0x17, 0xde, 0xad, 0x66, 0x3d, 0x91, 0x1d, 0xb4, 0x54, 0xbe, 0x89,
	0xf1, 0x08, 0xb1, 0x81, 0x8f, 0x15, 0xc8, 0x14, 0xc7, 0xe2, 0x15, 0xe2, 0x3d, 0xe3, 0x6d, 0x21,
	0x33, 0xff, 0xce, 0x01, 0x00, 0x00, 0xff, 0xff, 0x21, 0xcb, 0xd7, 0x29, 0x04, 0x01, 0x00, 0x00,
}
